create table iot_values_rp_2024
(
    id                  bigint generated by default as identity,
    air_temperature     double precision,
    apparent_wind_angle double precision,
    apparent_wind_speed double precision,
    asset_id           varchar(3),
    barometric_pressure double precision,
    course_over_ground  double precision,
    hdop                double precision,
    heading_true        double precision,
    lateral_speed_bow   double precision,
    lateral_speed_stern double precision,
    longitudinal_speed  double precision,
    position            varchar(255),
    rate_of_turn        double precision,
    real_time           boolean,
    river_code          varchar(255),
    river_mile          double precision,
    speed_over_ground   double precision,
    time                timestamp,
    vessel_airdraft     double precision,
    vessel_beam         double precision,
    vessel_draft        double precision,
    vessel_length       double precision,
    depth double precision,
    water_temperature double precision

) PARTITION BY RANGE (EXTRACT(QUARTER FROM time));

ALTER TABLE iot_values_rp_2024 OWNER TO "backup-prod";


CREATE TABLE iot_values_rp_2024_q1 PARTITION OF iot_values_rp_2024 FOR VALUES FROM (1) TO (2) PARTITION BY LIST (asset_id);
CREATE TABLE iot_values_rp_2024_q2 PARTITION OF iot_values_rp_2024 FOR VALUES FROM (2) TO (3) PARTITION BY LIST (asset_id);
CREATE TABLE iot_values_rp_2024_q3 PARTITION OF iot_values_rp_2024 FOR VALUES FROM (3) TO (4) PARTITION BY LIST (asset_id);
CREATE TABLE iot_values_rp_2024_q4 PARTITION OF iot_values_rp_2024 FOR VALUES FROM (4) TO (5) PARTITION BY LIST (asset_id);

CREATE TABLE iot_values_rp_2024_q1_EPJ PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('EPJ') ;
CREATE TABLE iot_values_rp_2024_q2_EPJ PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('EPJ');
CREATE TABLE iot_values_rp_2024_q3_EPJ PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('EPJ');
CREATE TABLE iot_values_rp_2024_q4_EPJ PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('EPJ');

CREATE TABLE iot_values_rp_2024_q1_BUL PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('BUL');
CREATE TABLE iot_values_rp_2024_q2_BUL PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('BUL');
CREATE TABLE iot_values_rp_2024_q3_BUL PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('BUL');
CREATE TABLE iot_values_rp_2024_q4_BUL PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('BUL');

CREATE TABLE iot_values_rp_2024_q1_CA PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('CA');
CREATE TABLE iot_values_rp_2024_q2_CA PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('CA');
CREATE TABLE iot_values_rp_2024_q3_CA PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('CA');
CREATE TABLE iot_values_rp_2024_q4_CA PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('CA');

CREATE TABLE iot_values_rp_2024_q1_CTW PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('CTW');
CREATE TABLE iot_values_rp_2024_q2_CTW PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('CTW');
CREATE TABLE iot_values_rp_2024_q3_CTW PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('CTW');
CREATE TABLE iot_values_rp_2024_q4_CTW PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('CTW');

CREATE TABLE iot_values_rp_2024_q1_COU PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('COU');
CREATE TABLE iot_values_rp_2024_q2_COU PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('COU');
CREATE TABLE iot_values_rp_2024_q3_COU PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('COU');
CREATE TABLE iot_values_rp_2024_q4_COU PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('COU');

CREATE TABLE iot_values_rp_2024_q1_DBL PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('DBL');
CREATE TABLE iot_values_rp_2024_q2_DBL PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('DBL');
CREATE TABLE iot_values_rp_2024_q3_DBL PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('DBL');
CREATE TABLE iot_values_rp_2024_q4_DBL PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('DBL');

CREATE TABLE iot_values_rp_2024_q1_ELL PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('ELL');
CREATE TABLE iot_values_rp_2024_q2_ELL PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('ELL');
CREATE TABLE iot_values_rp_2024_q3_ELL PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('ELL');
CREATE TABLE iot_values_rp_2024_q4_ELL PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('ELL');

CREATE TABLE iot_values_rp_2024_q1_EJH PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('EJH');
CREATE TABLE iot_values_rp_2024_q2_EJH PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('EJH');
CREATE TABLE iot_values_rp_2024_q3_EJH PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('EJH');
CREATE TABLE iot_values_rp_2024_q4_EJH PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('EJH');


CREATE TABLE iot_values_rp_2024_q1_FJG PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('FJG');
CREATE TABLE iot_values_rp_2024_q2_FJG PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('FJG');
CREATE TABLE iot_values_rp_2024_q3_FJG PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('FJG');
CREATE TABLE iot_values_rp_2024_q4_FJG PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('FJG');

CREATE TABLE iot_values_rp_2024_q1_GEO PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('GEO');
CREATE TABLE iot_values_rp_2024_q2_GEO PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('GEO');
CREATE TABLE iot_values_rp_2024_q3_GEO PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('GEO');
CREATE TABLE iot_values_rp_2024_q4_GEO PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('GEO');

-- CREATE TABLE iot_values_rp_2024_q1_MAJ PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('MAJ');
-- CREATE TABLE iot_values_rp_2024_q2_MAJ PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('MAJ');
-- CREATE TABLE iot_values_rp_2024_q3_MAJ PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('MAJ');
-- CREATE TABLE iot_values_rp_2024_q4_MAJ PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('MAJ');

CREATE TABLE iot_values_rp_2024_q1_HVY PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('HVY');
CREATE TABLE iot_values_rp_2024_q2_HVY PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('HVY');
CREATE TABLE iot_values_rp_2024_q3_HVY PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('HVY');
CREATE TABLE iot_values_rp_2024_q4_HVY PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('HVY');

CREATE TABLE iot_values_rp_2024_q1_HMM PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('HMM');
CREATE TABLE iot_values_rp_2024_q2_HMM PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('HMM');
CREATE TABLE iot_values_rp_2024_q3_HMM PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('HMM');
CREATE TABLE iot_values_rp_2024_q4_HMM PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('HMM');

CREATE TABLE iot_values_rp_2024_q1_HAM PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('HAM');
CREATE TABLE iot_values_rp_2024_q2_HAM PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('HAM');
CREATE TABLE iot_values_rp_2024_q3_HAM PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('HAM');
CREATE TABLE iot_values_rp_2024_q4_HAM PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('HAM');

CREATE TABLE iot_values_rp_2024_q1_INN PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('INN');
CREATE TABLE iot_values_rp_2024_q2_INN PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('INN');
CREATE TABLE iot_values_rp_2024_q3_INN PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('INN');
CREATE TABLE iot_values_rp_2024_q4_INN PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('INN');

CREATE TABLE iot_values_rp_2024_q1_INT PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('INT');
CREATE TABLE iot_values_rp_2024_q2_INT PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('INT');
CREATE TABLE iot_values_rp_2024_q3_INT PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('INT');
CREATE TABLE iot_values_rp_2024_q4_INT PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('INT');

CREATE TABLE iot_values_rp_2024_q1_JMK PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('JMK');
CREATE TABLE iot_values_rp_2024_q2_JMK PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('JMK');
CREATE TABLE iot_values_rp_2024_q3_JMK PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('JMK');
CREATE TABLE iot_values_rp_2024_q4_JMK PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('JMK');

CREATE TABLE iot_values_rp_2024_q1_JMJ PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('JMJ');
CREATE TABLE iot_values_rp_2024_q2_JMJ PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('JMJ');
CREATE TABLE iot_values_rp_2024_q3_JMJ PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('JMJ');
CREATE TABLE iot_values_rp_2024_q4_JMJ PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('JMJ');

CREATE TABLE iot_values_rp_2024_q1_KLH PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('KLH');
CREATE TABLE iot_values_rp_2024_q2_KLH PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('KLH');
CREATE TABLE iot_values_rp_2024_q3_KLH PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('KLH');
CREATE TABLE iot_values_rp_2024_q4_KLH PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('KLH');

CREATE TABLE iot_values_rp_2024_q1_LJ PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LJ');
CREATE TABLE iot_values_rp_2024_q2_LJ PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LJ');
CREATE TABLE iot_values_rp_2024_q3_LJ PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LJ');
CREATE TABLE iot_values_rp_2024_q4_LJ PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LJ');

CREATE TABLE iot_values_rp_2024_q1_LKC PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LKC');
CREATE TABLE iot_values_rp_2024_q2_LKC PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LKC');
CREATE TABLE iot_values_rp_2024_q3_LKC PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LKC');
CREATE TABLE iot_values_rp_2024_q4_LKC PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LKC');

CREATE TABLE iot_values_rp_2024_q1_LMT PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LMT');
CREATE TABLE iot_values_rp_2024_q2_LMT PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LMT');
CREATE TABLE iot_values_rp_2024_q3_LMT PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LMT');
CREATE TABLE iot_values_rp_2024_q4_LMT PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LMT');

CREATE TABLE iot_values_rp_2024_q1_LIB PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LIB');
CREATE TABLE iot_values_rp_2024_q2_LIB PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LIB');
CREATE TABLE iot_values_rp_2024_q3_LIB PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LIB');
CREATE TABLE iot_values_rp_2024_q4_LIB PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LIB');

CREATE TABLE iot_values_rp_2024_q1_LIZ PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LIZ');
CREATE TABLE iot_values_rp_2024_q2_LIZ PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LIZ');
CREATE TABLE iot_values_rp_2024_q3_LIZ PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LIZ');
CREATE TABLE iot_values_rp_2024_q4_LIZ PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LIZ');

CREATE TABLE iot_values_rp_2024_q1_LLP PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LLP');
CREATE TABLE iot_values_rp_2024_q2_LLP PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LLP');
CREATE TABLE iot_values_rp_2024_q3_LLP PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LLP');
CREATE TABLE iot_values_rp_2024_q4_LLP PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LLP');

CREATE TABLE iot_values_rp_2024_q1_LB PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LB');
CREATE TABLE iot_values_rp_2024_q2_LB PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LB');
CREATE TABLE iot_values_rp_2024_q3_LB PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LB');
CREATE TABLE iot_values_rp_2024_q4_LB PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LB');

CREATE TABLE iot_values_rp_2024_q1_LC PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('LC');
CREATE TABLE iot_values_rp_2024_q2_LC PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('LC');
CREATE TABLE iot_values_rp_2024_q3_LC PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('LC');
CREATE TABLE iot_values_rp_2024_q4_LC PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('LC');

CREATE TABLE iot_values_rp_2024_q1_MLL PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('MLL');
CREATE TABLE iot_values_rp_2024_q2_MLL PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('MLL');
CREATE TABLE iot_values_rp_2024_q3_MLL PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('MLL');
CREATE TABLE iot_values_rp_2024_q4_MLL PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('MLL');

CREATE TABLE iot_values_rp_2024_q1_MJ PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('MJ');
CREATE TABLE iot_values_rp_2024_q2_MJ PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('MJ');
CREATE TABLE iot_values_rp_2024_q3_MJ PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('MJ');
CREATE TABLE iot_values_rp_2024_q4_MJ PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('MJ');

CREATE TABLE iot_values_rp_2024_q1_SHL PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('SHL');
CREATE TABLE iot_values_rp_2024_q2_SHL PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('SHL');
CREATE TABLE iot_values_rp_2024_q3_SHL PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('SHL');
CREATE TABLE iot_values_rp_2024_q4_SHL PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('SHL');

CREATE TABLE iot_values_rp_2024_q1_SPT PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('SPT');
CREATE TABLE iot_values_rp_2024_q2_SPT PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('SPT');
CREATE TABLE iot_values_rp_2024_q3_SPT PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('SPT');
CREATE TABLE iot_values_rp_2024_q4_SPT PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('SPT');

CREATE TABLE iot_values_rp_2024_q1_SJG PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('SJG');
CREATE TABLE iot_values_rp_2024_q2_SJG PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('SJG');
CREATE TABLE iot_values_rp_2024_q3_SJG PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('SJG');
CREATE TABLE iot_values_rp_2024_q4_SJG PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('SJG');

CREATE TABLE iot_values_rp_2024_q1_SLS PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('SLS');
CREATE TABLE iot_values_rp_2024_q2_SLS PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('SLS');
CREATE TABLE iot_values_rp_2024_q3_SLS PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('SLS');
CREATE TABLE iot_values_rp_2024_q4_SLS PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('SLS');

CREATE TABLE iot_values_rp_2024_q1_WH PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('WH');
CREATE TABLE iot_values_rp_2024_q2_WH PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('WH');
CREATE TABLE iot_values_rp_2024_q3_WH PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('WH');
CREATE TABLE iot_values_rp_2024_q4_WH PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('WH');

CREATE TABLE iot_values_rp_2024_q1_BRS PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('BRS');
CREATE TABLE iot_values_rp_2024_q2_BRS PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('BRS');
CREATE TABLE iot_values_rp_2024_q3_BRS PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('BRS');
CREATE TABLE iot_values_rp_2024_q4_BRS PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('BRS');


CREATE TABLE iot_values_rp_2024_q1_BAS PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('BAS');
CREATE TABLE iot_values_rp_2024_q2_BAS PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('BAS');
CREATE TABLE iot_values_rp_2024_q3_BAS PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('BAS');
CREATE TABLE iot_values_rp_2024_q4_BAS PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('BAS');

CREATE TABLE iot_values_rp_2024_q1_GJM PARTITION OF iot_values_rp_2024_q1 FOR VALUES IN ('GJM');
CREATE TABLE iot_values_rp_2024_q2_GJM PARTITION OF iot_values_rp_2024_q2 FOR VALUES IN ('GJM');
CREATE TABLE iot_values_rp_2024_q3_GJM PARTITION OF iot_values_rp_2024_q3 FOR VALUES IN ('GJM');
CREATE TABLE iot_values_rp_2024_q4_GJM PARTITION OF iot_values_rp_2024_q4 FOR VALUES IN ('GJM');