create table iot_values_rp_2023
(
    id                  bigint generated by default as identity,
    air_temperature     double precision,
    apparent_wind_angle double precision,
    apparent_wind_speed double precision,
    asset_id            varchar(255),
    barometric_pressure double precision,
    course_over_ground  double precision,
    hdop                double precision,
    heading_true        double precision,
    lateral_speed_bow   double precision,
    lateral_speed_stern double precision,
    longitudinal_speed  double precision,
    position            varchar(255),
    rate_of_turn        double precision,
    real_time           boolean,
    river_code          varchar(255),
    river_mile          double precision,
    speed_over_ground   double precision,
    time                timestamp,
    vessel_airdraft     double precision,
    vessel_beam         double precision,
    vessel_draft        double precision,
    vessel_length       double precision

)PARTITION BY RANGE (EXTRACT(QUARTER FROM time));


CREATE TABLE iot_values_rp_2023_q1 PARTITION OF iot_values_rp_2023 FOR VALUES FROM (1) TO (2) PARTITION BY LIST (asset_id);

CREATE TABLE iot_values_rp_2023_q2 PARTITION OF iot_values_rp_2023 FOR VALUES FROM (2) TO (3) PARTITION BY LIST (asset_id);

CREATE TABLE iot_values_rp_2023_q3 PARTITION OF iot_values_rp_2023 FOR VALUES FROM (3) TO (4) PARTITION BY LIST (asset_id);

CREATE TABLE iot_values_rp_2023_q4 PARTITION OF iot_values_rp_2023 FOR VALUES FROM (4) TO (5) PARTITION BY LIST (asset_id);


CREATE TABLE iot_values_rp_2023_q1_EPJ PARTITION OF iot_values_rp_2023_q1 FOR VALUES IN ('562115');
CREATE TABLE iot_values_rp_2023_q2_EPJ PARTITION OF iot_values_rp_2023_q2 FOR VALUES IN ('562115');
CREATE TABLE iot_values_rp_2023_q3_EPJ PARTITION OF iot_values_rp_2023_q3 FOR VALUES IN ('562115');
CREATE TABLE iot_values_rp_2023_q4_EPJ PARTITION OF iot_values_rp_2023_q4 FOR VALUES IN ('562115');
